spring.application.name=01-SSF
spring.datasource.url= jdbc:oracle:thin:@//localhost:1521/orcl
spring.datasource.username=scott
spring.datasource.password=Rajdeep123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#agar table nhi hogi toh  bana dega --> create table dynamically
spring.jpa.hibernate.ddl-auto=update

#print sql queries on the console --> kon si query chali hai print karega 
spring.jpa.show-sql=true


spring.main.allow-circular-references=true